from src.linked_list import Linked_List
from randomgenius import getData

if __name__ == '__main__':
    print('##############################')
    linked_list = Linked_List()
    for x in range(5):
        linked_list.append(getData())
    print(f"5 random songs was appended to list")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    song_names = list()
    for x in range(5):
        song_names.append(getData())
    linked_list.append_list(song_names)
    print('\n\n')
    print(f"A list of 5 songs was just appened to the end of this linked list")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    linked_list.prepend(getData())
    print('\n\n')
    print(f"A random song was prepended to list")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()  
    linked_list.insert(getData(), 3)
    print('\n\n')
    print(f"Random Song was just inserted into index 3")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    linked_list.delete(song_names[1])
    print('\n\n')
    print(song_names[1] + " was removed from list")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    linked_list.reverse()
    print('\n\n')
    print("Reverse List")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()  
    temp_find = linked_list.find(song_names[2])
    print('\n\n')
    print(song_names[2] + " was searched for in the list")
    print(f"Find: {temp_find}")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    temp_data = linked_list.get(5)
    print('\n\n')
    print("get index 5")
    print(f"Index 5: {temp_data}")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    linked_list.remove_by_index(5)
    print('\n\n')
    print("remove index 5")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()
    linked_list.clear()
    print('\n\n')
    print("clear list")
    print(f"Size: {linked_list.get_size()}")
    linked_list.print_songs()


